"""
app/utils/validators.py — Input validation helper functions.

Provides reusable validation utilities for API request payloads.
These validators are called at the start of each API endpoint handler
to sanitise and reject invalid inputs early, before any business logic runs.

TODO (Phase 2): Implement the following validation functions.
"""

from __future__ import annotations
from typing import Any


def validate_email_input(data: dict[str, Any]) -> tuple[bool, str | None]:
    """
    Validate the request body for the POST /api/analyse endpoint.

    Checks that the request contains usable email content — either a
    non-empty 'raw_email' string, or an uploaded file.

    Args:
        data: Parsed JSON request body dictionary (may be empty if the
              request uses multipart/form-data instead of JSON).

    Returns:
        tuple[bool, str | None]: (is_valid, error_message)
            is_valid is True if the input passes all checks.
            error_message is None if valid, otherwise a human-readable
            description of the validation failure.

    Example:
        >>> valid, err = validate_email_input({"raw_email": "From: ..."})
        >>> valid
        True
        >>> valid, err = validate_email_input({})
        >>> valid
        False
        >>> err
        'No email content provided.'
    """
    # TODO (Phase 2): Implement
    raise NotImplementedError("validators.validate_email_input is not yet implemented.")


def validate_session_id(session_id: str) -> bool:
    """
    Validate that a session ID is a non-empty alphanumeric string.

    Session IDs are generated by the frontend (UUID v4 format expected)
    and must not be empty, excessively long, or contain special characters.

    Args:
        session_id: The session identifier string to validate.

    Returns:
        bool: True if the session_id is valid, False otherwise.
    """
    # TODO (Phase 2): Implement (UUID format check, length limit)
    raise NotImplementedError("validators.validate_session_id is not yet implemented.")


def validate_answer(answer: str) -> bool:
    """
    Validate that a submitted scenario answer is 'phishing' or 'legitimate'.

    Args:
        answer: The answer string submitted by the user.

    Returns:
        bool: True only if answer is exactly 'phishing' or 'legitimate'
              (case-insensitive).
    """
    return answer.lower() in ("phishing", "legitimate")
